### PR TITLE
adding required codes to add_setting()

### PR DESCRIPTION
**Pull request by robertdevore**

### CODE REVIEW

**Comment by deviodigital** [comment]
Not sure if I did something wrong, but it's showing 6 files updated, 3 files double, each with a ~ on the end of the file name.

First time issuing a pull request, so I don't know if I fucked something up or not. If I did, just yell at me until I cry, and then I'll fix it :)

**Comment by tommcfarlin** [comment]
When you went about making the changes to the files in order to issue the pull requests, what steps did you take?

- Did you create new files and then paste content in from the original?
- Did you edit the existing files?
- Did you do something else?

:)

Let me know as it'll help me know how to move forward from here.

**Comment by deviodigital** [comment]
I actually followed this tutorial on how to do it:

http://stackoverflow.com/a/14680805

If it helps, in my local folder, I don't see any extra files with the ~ at the end of it.

**Comment by tommcfarlin** [comment]
I'll merge it and then do a rollback. I'm not really sure what happened but the easiest thing for me to do at this point is to merge and then undo these changes.

**Pull request merged**
